version: '3'

services:
  postgres:
    container_name: joke_machine_postgres
    image: postgres:10.6-alpine
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: ${USER}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    container_name: joke_machine_redis
    image: redis:4.0.12-alpine
    ports:
      - '127.0.0.1:6379:6379'
  maildev:
    container_name: joke_machine_maildev
    image: djfarrelly/maildev:latest
    ports:
      - '127.0.0.1:1080:80'
      - '127.0.0.1:1025:25'