
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: joke_machine_development

test:
  <<: *default
  database: joke_machine_test

production:
  url: <%= ENV['DATABASE_URL'] %>